version: "3.8"
services:
  db:
    container_name: nest-graphql-auth-db
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
  redis:
    container_name: nest-graphql-auth-redis
    image: redis:alpine
    command: redis-server --requirepass 40028922
    ports:
      - "6379:6379"
  app:
    container_name: nest-graphql-auth-app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "wait-for-it.sh db:5432 && pnpm prisma migrate deploy && pnpm start:dev"
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:docker@db:5432/dev
      - MAIL_REDIS_HOST=redis
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db
      - redis
